name: CI

on: [push, pull_request]

jobs:
  core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew \
            :protocol:test \
            :client-core:test \
            :transport-adb:test \
            :server-android:assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: |
            server-android/build/outputs/apk/**/*.apk
          retention-days: 7


  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: .\gradlew.bat build packageRelease

      - name: Upload Windows package
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: |
            **/build/**/*.exe
            **/build/**/*.msi
            **/build/**/*.zip
          retention-days: 7
